// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgvQFCcT-jP6Q5niGc70iPTO0laaOu4xM',
    appId: '1:1040137796522:web:a0bdfd681e0b876fd689d3',
    messagingSenderId: '1040137796522',
    projectId: 'lab009-9ffd3',
    authDomain: 'lab009-9ffd3.firebaseapp.com',
    storageBucket: 'lab009-9ffd3.appspot.com',
    measurementId: 'G-ZBL41XXW2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ7R-0f0ImXuH_3og5MMDjPxhgtIYr_aQ',
    appId: '1:1040137796522:android:e6a5aee845c85275d689d3',
    messagingSenderId: '1040137796522',
    projectId: 'lab009-9ffd3',
    storageBucket: 'lab009-9ffd3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw-u-O1z2MVVUyGCsZWBIAbek0n0fqHpQ',
    appId: '1:1040137796522:ios:bbbd1daa1d67895dd689d3',
    messagingSenderId: '1040137796522',
    projectId: 'lab009-9ffd3',
    storageBucket: 'lab009-9ffd3.appspot.com',
    iosClientId: '1040137796522-fcv21b6mcmbfcjf96uaa7gka3ten23aa.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab009',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw-u-O1z2MVVUyGCsZWBIAbek0n0fqHpQ',
    appId: '1:1040137796522:ios:bbbd1daa1d67895dd689d3',
    messagingSenderId: '1040137796522',
    projectId: 'lab009-9ffd3',
    storageBucket: 'lab009-9ffd3.appspot.com',
    iosClientId: '1040137796522-fcv21b6mcmbfcjf96uaa7gka3ten23aa.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab009',
  );
}
